//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodeng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public int RetailStoreId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string Supplier { get; set; }
        public int StockQuantity { get; set; }
        public Nullable<int> LowStockThreshold { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual RetailStore RetailStore { get; set; }
    }
}
