//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodeng
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int MembershipId { get; set; }
        public string CustomerId { get; set; }
        public int RetailStoreId { get; set; }
        public Nullable<System.DateTime> MembershipDate { get; set; }
        public string MembershipStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual RetailStore RetailStore { get; set; }
    }
}
