//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodeng
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public int ReportId { get; set; }
        public int RetailStoreId { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<int> TotalOrders { get; set; }
    
        public virtual RetailStore RetailStore { get; set; }
    }
}
